import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma";
import { requireAuth, requireOrganizerAccess } from "../middleware/auth";
import { organizerIdsWithPermission } from "../lib/access";
import { exhibitionMutationRateLimit } from "../middleware/rateLimit";
import { logAudit } from "../lib/audit";

const router = Router();
router.use(requireAuth, requireOrganizerAccess);

const statusSchema = z.enum(["active","inactive","archived"]);
const typeSchema = z.enum(["fixed","movable","bleacher","auditorium","classroom","theater","banquet","cabaret","other"]);
const createSchema = z.object({
  name:z.string().trim().min(1).max(160), code:z.string().trim().min(1).max(80).nullable().optional(),
  description:z.string().trim().max(5000).nullable().optional(), type:typeSchema.optional(),
  floorId:z.string().uuid().nullable().optional(), spaceId:z.string().uuid().nullable().optional(),
  capacity:z.number().int().min(1).max(1000000), accessibleSeats:z.number().int().min(0).max(1000000).optional(),
  rowCount:z.number().int().min(1).max(10000).nullable().optional(), seatsPerRow:z.number().int().min(1).max(10000).nullable().optional(),
  sortOrder:z.number().int().min(0).max(100000).optional(),
});
const updateSchema=createSchema.partial().extend({status:statusSchema.optional()});

async function venueFor(user: import("@prisma/client").User,id:string,p:"venue:view"|"venue:manage"){const ids=await organizerIdsWithPermission(user,p);return ids.length?prisma.venue.findFirst({where:{id,organizerId:{in:ids}}}):null;}
async function seatingFor(user: import("@prisma/client").User,id:string,p:"venue:view"|"venue:manage"){const ids=await organizerIdsWithPermission(user,p);return ids.length?prisma.venueSeatingArea.findFirst({where:{id,venue:{organizerId:{in:ids}}}}):null;}
function counts(input:{capacity:number;accessibleSeats?:number|null;rowCount?:number|null;seatsPerRow?:number|null}){const a=input.accessibleSeats??0;if(a>input.capacity)return "Accessible seats cannot exceed seating capacity.";if(input.rowCount&&input.seatsPerRow&&input.rowCount*input.seatsPerRow>input.capacity)return "Rows multiplied by seats per row cannot exceed capacity.";return null;}
async function location(venueId:string,floorId?:string|null,spaceId?:string|null){
 if(floorId){const f=await prisma.venueFloor.findFirst({where:{id:floorId,building:{venueId}},select:{id:true,archivedAt:true,building:{select:{archivedAt:true}}}});if(!f)return "Floor does not belong to this venue.";if(f.archivedAt||f.building.archivedAt)return "Cannot use an archived floor or building.";}
 if(spaceId){const s=await prisma.venueSpace.findFirst({where:{id:spaceId,zone:{floor:{building:{venueId}}}},select:{id:true,archivedAt:true,zone:{select:{floorId:true,archivedAt:true,floor:{select:{archivedAt:true,building:{select:{archivedAt:true}}}}}}}});if(!s)return "Space does not belong to this venue.";if(s.archivedAt||s.zone.archivedAt||s.zone.floor.archivedAt||s.zone.floor.building.archivedAt)return "Cannot use an archived space, zone, floor, or building.";if(floorId&&s.zone.floorId!==floorId)return "Space must belong to the selected floor.";}return null;
}
function conflict(res:import("express").Response,e:unknown){if(e&&typeof e==="object"&&"code"in e&&e.code==="P2002")return res.status(409).json({error:"A seating area with the same name or code already exists for this venue."});throw e;}

router.get("/venues/:venueId/seating",async(req,res)=>{const v=await venueFor(req.user!,req.params.venueId,"venue:view");if(!v)return res.status(404).json({error:"Venue not found"});const status=typeof req.query.status==="string"&&statusSchema.safeParse(req.query.status).success?req.query.status as "active"|"inactive"|"archived":undefined;const type=typeof req.query.type==="string"&&typeSchema.safeParse(req.query.type).success?req.query.type as z.infer<typeof typeSchema>:undefined;const q=typeof req.query.q==="string"?req.query.q.trim():"";const seatingAreas=await prisma.venueSeatingArea.findMany({where:{venueId:v.id,...(status?{status}:{status:{not:"archived"}}),...(type?{type}:{}),...(q?{OR:[{name:{contains:q,mode:"insensitive"}},{code:{contains:q,mode:"insensitive"}}]}:{})},orderBy:[{sortOrder:"asc"},{name:"asc"}]});return res.json({seatingAreas});});
router.get("/seating/:id",async(req,res)=>{const s=await seatingFor(req.user!,req.params.id,"venue:view");if(!s)return res.status(404).json({error:"Seating area not found"});return res.json({seatingArea:s});});
router.post("/venues/:venueId/seating",exhibitionMutationRateLimit,async(req,res)=>{const p=createSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.issues[0].message});const v=await venueFor(req.user!,req.params.venueId,"venue:manage");if(!v)return res.status(404).json({error:"Venue not found"});if(v.archivedAt)return res.status(409).json({error:"Cannot add seating to an archived venue"});const ce=counts(p.data);if(ce)return res.status(400).json({error:ce});const le=await location(v.id,p.data.floorId,p.data.spaceId);if(le)return res.status(400).json({error:le});try{const s=await prisma.venueSeatingArea.create({data:{...p.data,venueId:v.id}});await logAudit({actorUserId:req.user!.id,action:"venue.seating.created",entityType:"VenueSeatingArea",entityId:s.id,metadata:{venueId:v.id}});return res.status(201).json({seatingArea:s});}catch(e){return conflict(res,e);}});
router.patch("/seating/:id",exhibitionMutationRateLimit,async(req,res)=>{const p=updateSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.issues[0].message});const current=await seatingFor(req.user!,req.params.id,"venue:manage");if(!current)return res.status(404).json({error:"Seating area not found"});if(current.archivedAt&&p.data.status!=="archived")return res.status(409).json({error:"This seating area is archived. Restore it before editing."});const merged={capacity:p.data.capacity??current.capacity,accessibleSeats:p.data.accessibleSeats??current.accessibleSeats,rowCount:p.data.rowCount??current.rowCount,seatsPerRow:p.data.seatsPerRow??current.seatsPerRow};const ce=counts(merged);if(ce)return res.status(400).json({error:ce});if(p.data.floorId!==undefined||p.data.spaceId!==undefined){const le=await location(current.venueId,p.data.floorId??current.floorId,p.data.spaceId??current.spaceId);if(le)return res.status(400).json({error:le});}try{const s=await prisma.venueSeatingArea.update({where:{id:current.id},data:{...p.data,archivedAt:p.data.status==="archived"?(current.archivedAt??new Date()):p.data.status?null:undefined}});await logAudit({actorUserId:req.user!.id,action:"venue.seating.updated",entityType:"VenueSeatingArea",entityId:s.id,metadata:{venueId:s.venueId,changedFields:Object.keys(p.data)}});return res.json({seatingArea:s});}catch(e){return conflict(res,e);}});
router.delete("/seating/:id",exhibitionMutationRateLimit,async(req,res)=>{const s=await seatingFor(req.user!,req.params.id,"venue:manage");if(!s)return res.status(404).json({error:"Seating area not found"});if(s.archivedAt)return res.status(204).send();await prisma.venueSeatingArea.update({where:{id:s.id},data:{status:"archived",archivedAt:new Date()}});await logAudit({actorUserId:req.user!.id,action:"venue.seating.archived",entityType:"VenueSeatingArea",entityId:s.id,metadata:{venueId:s.venueId}});return res.status(204).send();});
router.post("/seating/:id/restore",exhibitionMutationRateLimit,async(req,res)=>{const s=await seatingFor(req.user!,req.params.id,"venue:manage");if(!s)return res.status(404).json({error:"Seating area not found"});if(!s.archivedAt)return res.status(400).json({error:"Seating area is not archived"});const v=await venueFor(req.user!,s.venueId,"venue:manage");if(!v||v.archivedAt)return res.status(409).json({error:"Cannot restore seating under an archived venue"});const le=await location(s.venueId,s.floorId,s.spaceId);if(le)return res.status(409).json({error:le});const restored=await prisma.venueSeatingArea.update({where:{id:s.id},data:{status:"active",archivedAt:null}});await logAudit({actorUserId:req.user!.id,action:"venue.seating.restored",entityType:"VenueSeatingArea",entityId:restored.id,metadata:{venueId:restored.venueId}});return res.json({seatingArea:restored});});
export default router;
