-- Phase 6.3K — participant lifecycle notifications extend the existing in-app notification enum.
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_SESSION_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_SPONSOR_PACKAGE_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PARTICIPANT_VENDOR_SERVICE_ASSIGNED';
