// AVM-09 seating regression tests
import assert from "node:assert/strict";
import { test, before, after } from "node:test";
import { prisma } from "../src/lib/prisma";
import { startTestServer } from "./helpers/testServer";
let baseUrl:string; let stop:()=>Promise<void>; const ts=Date.now();
before(async()=>{({baseUrl,stop}=await startTestServer());}); after(async()=>{await stop();});
async function bootstrap(label:string){const r=await fetch(`${baseUrl}/api/auth/signup`,{method:"POST",headers:{"Content-Type":"application/json","X-Test-Rate-Limit-Key":`avm09-${label}`},body:JSON.stringify({email:`avm09-${label}-${ts}@example.com`,password:"TestPassword123!",fullName:`AVM09 ${label}`,userType:"exhibitor"})});const b=await r.json();assert.equal(r.status,201);await fetch(`${baseUrl}/api/exhibitions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${b.token}`},body:JSON.stringify({name:`AVM09 bootstrap ${label} ${ts}`,status:"draft",visibility:"public",ticketTypes:[],stalls:[]})});return b.token as string;}
async function venue(t:string,l:string){const r=await fetch(`${baseUrl}/api/venues`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({name:`AVM09 Venue ${l} ${ts}`})});assert.equal(r.status,201);return (await r.json()).venue.id as string;}
test("AVM-09 seating CRUD validation archive restore",async()=>{const t=await bootstrap("crud"),v=await venue(t,"crud");const bad=await fetch(`${baseUrl}/api/venue-seating/venues/${v}/seating`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({name:"Bad",capacity:10,accessibleSeats:11})});assert.equal(bad.status,400);const r=await fetch(`${baseUrl}/api/venue-seating/venues/${v}/seating`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({name:"Auditorium",code:"A1",type:"auditorium",capacity:500,accessibleSeats:20,rowCount:25,seatsPerRow:20})});assert.equal(r.status,201);const s=(await r.json()).seatingArea;const list=await fetch(`${baseUrl}/api/venue-seating/venues/${v}/seating?q=audit`,{headers:{Authorization:`Bearer ${t}`}});assert.equal(list.status,200);assert.equal((await list.json()).seatingAreas.length,1);const p=await fetch(`${baseUrl}/api/venue-seating/seating/${s.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({capacity:600,accessibleSeats:25})});assert.equal(p.status,200);const d=await fetch(`${baseUrl}/api/venue-seating/seating/${s.id}`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});assert.equal(d.status,204);assert.equal((await prisma.venueSeatingArea.findUniqueOrThrow({where:{id:s.id}})).status,"archived");const rr=await fetch(`${baseUrl}/api/venue-seating/seating/${s.id}/restore`,{method:"POST",headers:{Authorization:`Bearer ${t}`}});assert.equal(rr.status,200);});
test("AVM-09 tenant isolation",async()=>{const owner=await bootstrap("owner"),other=await bootstrap("other"),v=await venue(owner,"owner");const r=await fetch(`${baseUrl}/api/venue-seating/venues/${v}/seating`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${owner}`},body:JSON.stringify({name:"Main Seating",capacity:100})});assert.equal(r.status,201);const id=(await r.json()).seatingArea.id;const read=await fetch(`${baseUrl}/api/venue-seating/venues/${v}/seating`,{headers:{Authorization:`Bearer ${other}`}});assert.equal(read.status,404);const patch=await fetch(`${baseUrl}/api/venue-seating/seating/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${other}`},body:JSON.stringify({name:"Hacked"})});assert.equal(patch.status,404);});
