import assert from "node:assert/strict";
import { test, before, after } from "node:test";
import { prisma } from "../src/lib/prisma";
import { startTestServer } from "./helpers/testServer";
let baseUrl: string; let stop: () => Promise<void>; const ts = Date.now();
before(async () => { ({ baseUrl, stop } = await startTestServer()); });
after(async () => { await stop(); });
async function signup(label: string) { const res = await fetch(baseUrl + "/api/auth/signup", { method: "POST", headers: { "Content-Type": "application/json", "X-Test-Rate-Limit-Key": "staff-" + label }, body: JSON.stringify({ email: "staff-" + label + "-" + ts + "@example.com", password: "TestPassword123!", fullName: "Staff " + label, userType: "exhibitor" }) }); const body = await res.json(); return { token: body.token as string }; }
async function bootstrap(label: string) { const { token } = await signup(label); const res = await fetch(baseUrl + "/api/exhibitions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ name: "Staff bootstrap " + label + " " + ts, status: "draft", visibility: "public", ticketTypes: [], stalls: [] }) }); const body = await res.json(); const eventId = body.exhibition.eventId as string; const enable = await fetch(baseUrl + "/api/events/" + eventId + "/modules/PARTICIPANTS", { method: "PUT", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ enabled: true }) }); assert.equal(enable.status, 200); return { token, eventId }; }
test("staff management: create, search, update, archive and restore", async () => { const { token, eventId } = await bootstrap("crud"); const create = await fetch(baseUrl + "/api/events/" + eventId + "/staff", { method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ name: "Alex Staff", title: "Event Coordinator", organization: "ExhibitTix", email: "staff@example.com", isPublic: false, sortOrder: 1 }) }); assert.equal(create.status, 201); const created = await create.json(); const staffId = created.staff.id as string; assert.equal(created.staff.participantType, "STAFF"); const search = await fetch(baseUrl + "/api/events/" + eventId + "/staff?search=Alex", { headers: { Authorization: "Bearer " + token } }); assert.equal(search.status, 200); assert.equal((await search.json()).total, 1); const update = await fetch(baseUrl + "/api/events/" + eventId + "/staff/" + staffId, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ title: "Senior Event Coordinator" }) }); assert.equal(update.status, 200); assert.equal((await update.json()).staff.title, "Senior Event Coordinator"); const archive = await fetch(baseUrl + "/api/events/" + eventId + "/staff/" + staffId, { method: "DELETE", headers: { Authorization: "Bearer " + token } }); assert.equal(archive.status, 204); const hidden = await fetch(baseUrl + "/api/events/" + eventId + "/staff", { headers: { Authorization: "Bearer " + token } }); assert.equal((await hidden.json()).total, 0); const restore = await fetch(baseUrl + "/api/events/" + eventId + "/staff/" + staffId + "/restore", { method: "POST", headers: { Authorization: "Bearer " + token } }); assert.equal(restore.status, 200); });
test("staff management rejects mutation when participant module is disabled", async () => { const { token } = await signup("blocked"); const res = await fetch(baseUrl + "/api/exhibitions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ name: "Staff blocked " + ts, status: "draft", visibility: "public", ticketTypes: [], stalls: [] }) }); const body = await res.json(); const eventId = body.exhibition.eventId as string; const create = await fetch(baseUrl + "/api/events/" + eventId + "/staff", { method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ name: "Blocked Staff" }) }); assert.equal(create.status, 409); });
test("staff management keeps tenant boundary", async () => { const a = await bootstrap("cross-a"); const b = await bootstrap("cross-b"); const res = await fetch(baseUrl + "/api/events/" + a.eventId + "/staff", { headers: { Authorization: "Bearer " + b.token } }); assert.equal(res.status, 404); await prisma.eventParticipant.deleteMany({ where: { eventId: a.eventId } }); });
